services:
  windows:
    image: dockurr/windows
    container_name: windows7
    environment:
      VERSION: "win7"
      LANGUAGE: "pt-BR"
      TZ: "America/Sao_Paulo"
      LANG: "pt_BR.UTF-8"
      LC_ALL: "pt_BR.UTF-8"
      REGION: "pt-BR"      # Definindo a região como Brasil
      KEYBOARD: "br-abnt2" # Definindo o layout do teclado como ABNT2
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /home/user/example:/shared
      - /userdata/windows:/userdata/windows # Adicionando volume para /userdata/windows
    stop_grace_period: 2m
